### PR TITLE
Implement add command to add files to the index

### PR DESCRIPTION
**Pull request by ramsey**
This PR provides `git add` functionality for adding files to and updating the index.

## Example

```php
use SebastianFeldmann\Git;

$repo = new Git\Repository(__DIR__);
$index = $repo->getIndexOperator();

$index->addFilesToIndex(['.']);

foreach ($index->getStagedFiles() as $stagedFile) {
    echo $stagedFile . PHP_EOL;
}
```

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
What do you think about adding the `Operator` stuff to the existing `IndexOperator` (Operator\Index)?
Not sure if we should create an operator for every command, never the less that might me the cleanest solution 🤔

**Comment by ramsey** [comment]
This makes sense, especially since the files are being added to the index.

**Comment by ramsey** [comment]
I've updated this to get rid of the `Add` operator and move the methods into the `Index` operator.

I'm not sure why the tests are failing on PHP 8. I'm running 8.0.3 locally, and I can't reproduce the failure. It looks like it's having trouble with the unicode characters.

**Review by sebastianfeldmann — APPROVED** [review]
Looks great, tests are passing on my side as well. I will investigate this after the merge :)

**Pull request merged**
